# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - branch  # Запускать при пуше в ветку branch
  pull_request:
    branches:
      - branch  # Запускать при запросе на слияние в ветку branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          python3 -m unittest discover -s . -p "test_*.py"